#! /usr/bin/env perl

use strict;
use warnings;

$|++;

while (<>) {
	chomp;
	my @X = split;
	my $ret = "ERR";
	if (@X) {
		my $url = $X[0];
		if (($url =~ m/(https:\/\/.*youtube\.com\/watch\?v=.*)/) ||
		    ($url =~ m/(https:\/\/.*youtube\.com\/v\/.*)/)) {
			$ret = "OK rewrite-url=\"$1&html5=1\"";
		}
	}
	print "$ret\n";
}
